version: '3'

volumes:
  mysql-data:
    name: ${PROJECT_NAME}-data

networks:
  network-id:
    name: ${PROJECT_NAME}-network
    ipam:
      config:
        - subnet: 172.30.0.0/16

services:
  mysql:
    build:
      context: ./docker/mysql
      args:
        mysql_version: ${MYSQL_VERSION}
    container_name: ${PROJECT_NAME}-mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    command: ["--pid-file=/var/run/mysqld/mysqld.pid"]
    volumes:
      - mysql-data:/var/lib/mysql
      - ./src/db:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_PORT}:3306"
    restart: always
    networks:
      - network-id

  php:
    build:
      context: ./docker/php
      args:
        php_version: ${PHP_VERSION}
    container_name: ${PROJECT_NAME}-php
    ports:
      - "${PHP_PORT}:80"
    volumes:
      - ./src:/var/www/html
    links:
      - mysql
    networks:
      - network-id